#!/usr/bin/env node
/**
 * .agents/skills is the cross-tool source (Antigravity reads it by path). Claude Code only discovers
 * skills in .claude/skills, and loads each one when its description matches the task. This script
 * copies the knowledge skills there with "use when" descriptions. `--check` fails if the copies drifted.
 * Process roles (scrum master, product owner, growth) are intentionally not exported: you are the
 * product owner, CI is the release gate, and growth work waits for Phase 11.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(root, ".agents", "skills");
const target = join(root, ".claude", "skills");

const exported = {
  "role-backend-engineer":
    "Use when changing apps/api (Fastify routes, services, plugins), Prisma schema or migrations, BullMQ jobs, auth, or the ingestion pipeline.",
  "role-frontend-engineer":
    "Use when changing apps/web or packages/ui: Next.js pages, React Query hooks, Zustand state, Tailwind v4, Radix components, loading/empty/error states.",
  "role-realtime-engineer":
    "Use when touching Socket.IO, the Redis adapter or emitter, RealtimePublisher, room authorization, or reconnect behavior.",
  "role-security-engineer":
    "Use when touching auth, sessions, cookies, CSRF, rate limits, tenant isolation, API keys, secrets, webhooks or logging redaction.",
  "role-sdet-architect":
    "Use when writing or reviewing tests: acceptance tests first, tenant 404/403 matrices, concurrency tests, flakiness, coverage, SC-* traceability.",
  "role-devops-engineer":
    "Use when changing GitHub Actions, deploy workflows, render.yaml, environment variables, Turborepo config, or free-tier hosting.",
  "role-fullstack-architect":
    "Use when a change crosses packages, alters a canonical contract (master plan §4-§8), needs an ADR, or adds a new module boundary.",
  "dev-coding-standards":
    "Use when writing TypeScript in any workspace and you need the house rules for Fastify, Next.js, Prisma and Zod.",
};

function render(name, description) {
  const text = readFileSync(join(source, name, "SKILL.md"), "utf8").replace(/\r\n/g, "\n");
  const replaced = text.replace(/^description:.*$/m, `description: ${description}`);
  return `${replaced.replace(/^---\n/, `---\n# Generated by scripts/sync-skills.mjs from .agents/skills/${name}. Edit the source, then run npm run sync:skills.\n`)}`;
}

const check = process.argv.includes("--check");
const drift = [];
for (const [name, description] of Object.entries(exported)) {
  const expected = render(name, description);
  const file = join(target, name, "SKILL.md");
  if (check) {
    if (!existsSync(file) || readFileSync(file, "utf8").replace(/\r\n/g, "\n") !== expected) drift.push(name);
  } else {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, expected);
  }
}
if (!check && existsSync(target)) {
  for (const dir of readdirSync(target)) if (!(dir in exported)) rmSync(join(target, dir), { recursive: true });
}
if (drift.length > 0) {
  console.error(`.claude/skills is out of date for: ${drift.join(", ")}. Run npm run sync:skills.`);
  process.exit(1);
}
console.info(check ? "Skills are in sync." : `Synced ${Object.keys(exported).length} skills to .claude/skills.`);
